config/routes.rb
TheApp::Application.routes.draw do
  root to: 'welcome#index'

  # Legacy Urls
  # /recipes/rc56797---lavandovyy-limonad
  # /recipes/tags/milk
  get "recipes/:id" => "welcome#legacy_post"
  get "recipes/tag/:id", to: redirect { |params, request| URI.encode "#{request.protocol + request.host_with_port}/tag/#{params[:id]}" }

  # Login system
  get    "login"    => "sessions#new",     as: :login
  delete "logout"   => "sessions#destroy", as: :logout
  get    "signup"   => "users#new",        as: :signup
  post   "sessions" => "sessions#create",  as: :sessions

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # Direct routes
  %w{ hubs pages posts }.each do |name|
    resources name, concerns: :sortable_tree
  end

  resources :hubs do
    post :expand_node, on: :collection
    # post :selector,    on: :collection
  end

  # Users
  resources :users, only: [:index, :show, :create] do
    %w{ hubs pages posts }.each do |name|
      resources name, concerns: :sortable_tree
    end
  end

  # tags
  get "tag/:tag" => "posts#tag", as: :tag

  # /users/:user_id/manage/recipes
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage

  # TheStorages
  patch '/image_processor/rotate_left/:id',  as: :rotate_left,  to: 'image_processor#rotate_left'
  patch '/image_processor/rotate_right/:id', as: :rotate_right, to: 'image_processor#rotate_right'
  patch '/image_processor/crop_image',       as: :crop_image,   to: 'image_processor#crop_image'

  get "/:id" => 'hubs#system_section', as: :system_hub

  # Main image
  delete 'delete_main_image/:storage_type/:storage_id'   => "attached_files#delete_main_image",      as: :delete_main_image
  patch  'main_image_to_left/:storage_type/:storage_id'  => "attached_files#main_image_to_left",     as: :main_image_to_left
  patch  'main_image_to_right/:storage_type/:storage_id' => "attached_files#main_image_to_right",    as: :main_image_to_right
  post   'crop_image_for_preview'                        => "attached_files#crop_image_for_preview", as: :crop_image_for_preview
end

app/views/bootstrap3/shared/_crop_image_form.html.haml
= form_tag crop_image_for_preview_url, id: :main_image_cropping, class: :hidden do
  = text_field_tag :storage_type, object.class.to_s
  = text_field_tag :storage_id,   object.id

  = text_field_tag :x
  = text_field_tag :y
  = text_field_tag :w
  = text_field_tag :h
  = text_field_tag :img_w

app/views/bootstrap3/shared/_main_image_toolbar.html.haml
.image_toolbar
  .base_view
    %p
      %b= t('main_image.title') 

    - if object.main_image?  
      .rotate
        = link_to '', main_image_to_left_url(object.class.to_s, object.id),  method: :patch, class: :left
        = link_to '', main_image_to_right_url(object.class.to_s, object.id), method: :patch, class: :right
    .image_preview
      = link_to object.main_image.url(:preview) do
        = image_tag object.main_image.url(:preview), width: '100%'

    .tools_block
      - if object.main_image?
        = link_to '', |
        delete_main_image_url(object.class.to_s, object.id), |
        method: :delete, data: { confirm: "Вы уверены?" }, class: :img_clear

      %p
        %label= t('main_image.select')
        = f.file_field :main_image

      - if object.main_image?
        %p
          = link_to t('main_image.selected_area'), '#', method: :patch, class: :jcrop_run

  - if object.main_image?
    .crop_view
      %p
        %b= t('main_image.selecte_area_and_save')

      %div
        = image_tag object.main_image.url(:base), id: :main_image_jcrop

        .cropped_preview_holder
          .cropped_preview
            = image_tag object.main_image.url, id: :cropped_main_image_preview

        = submit_tag t('main_image.save'), id: :main_image_cropping_save, class: :hidden

      %p= link_to t('main_image.just_close'), '#', method: :patch, class: :jcrop_stop

=# render partial: 'the_storages/preview_maker', locals: { storage: object }

app/views/bootstrap3/shared/_meta_fields.html.haml
.form-group.meta_block
  = link_to '#' do
    = t 'pubs.seo_meta_info'
    %i.icon-arrow-down

.form-group.meta_fields.hidden
  - %w[ slug author keywords description copyright].each do |name|
    .form-group
      = f.label t(".#{name}")
      = f.text_field name, class: 'form-control'

app/views/bootstrap3/shared/_per_page.html.haml
.per_page
  = link_to t('per_page.5'),  '?per_page=5'
  = link_to t('per_page.10'), '?per_page=10'
  = link_to t('per_page.20'), '?per_page=20'
  = link_to t('per_page.50'), '?per_page=50'

app/views/bootstrap3/shared/_pub_stats.html.haml
- unless object.new_record?
  %nav.navbar.navbar-default{ role: :navigation }
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %p.navbar-text
            %b= t 'pubs.info.author'
            = object.user.login
        %li
          %p.navbar-text
            %b= t 'pubs.info.show_count'
            = object.show_count
        - if object.try(:pubs)
          %li
            %p.navbar-text
              %b= t 'pubs.info.pubs_count'
              = object.pubs.count
        %li
          %p.navbar-text
            %b= t 'pubs.info.files_count'
            = object.storage_files_count
        %li
          %p.navbar-text
            %b= t 'pubs.info.files_size'
            = raw mb_size(object.storage_files_size)

app/views/bootstrap3/shared/_top_fields.html.haml
= render partial: 'hubs/hub_select', locals: { object: object, selector_hubs: selector_hubs }
= render partial: "shared/meta_fields", locals: { f: f }