config/routes.rb
TheApp::Application.routes.draw do
  root to: 'welcome#index'

  # Legacy Urls
  # /recipes/rc56797---lavandovyy-limonad
  # /recipes/tags/milk
  get "recipes/:id" => "welcome#legacy_post"
  get "recipes/tag/:id", to: redirect { |params, request| URI.encode "#{request.protocol + request.host_with_port}/tag/#{params[:id]}" }

  # Login system
  get    "login"    => "sessions#new",     as: :login
  delete "logout"   => "sessions#destroy", as: :logout
  get    "signup"   => "users#new",        as: :signup
  post   "sessions" => "sessions#create",  as: :sessions

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # Direct routes
  %w{ hubs pages posts }.each do |name|
    resources name, concerns: :sortable_tree
  end

  resources :hubs do
    post :expand_node, on: :collection
    # post :selector,    on: :collection
  end

  # Users
  resources :users, only: [:index, :show, :create] do
    %w{ hubs pages posts }.each do |name|
      resources name, concerns: :sortable_tree
    end
  end

  # tags
  get "tag/:tag" => "posts#tag", as: :tag

  # /users/:user_id/manage/recipes
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage

  # TheStorages
  patch '/image_processor/rotate_left/:id',  as: :rotate_left,  to: 'image_processor#rotate_left'
  patch '/image_processor/rotate_right/:id', as: :rotate_right, to: 'image_processor#rotate_right'
  patch '/image_processor/crop_image',       as: :crop_image,   to: 'image_processor#crop_image'

  get "/:id" => 'hubs#system_section', as: :system_hub

  # Main image
  delete 'delete_main_image/:storage_type/:storage_id'   => "attached_files#delete_main_image",      as: :delete_main_image
  patch  'main_image_to_left/:storage_type/:storage_id'  => "attached_files#main_image_to_left",     as: :main_image_to_left
  patch  'main_image_to_right/:storage_type/:storage_id' => "attached_files#main_image_to_right",    as: :main_image_to_right
  post   'crop_image_for_preview'                        => "attached_files#crop_image_for_preview", as: :crop_image_for_preview
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  include DefineOpenPassword

  include TheRole::User
  
  include ActAsStorage
  include HasAttachedFiles

  include TheComments::User
  include TheComments::Commentable

  def to_param; self.login end

  # Relations
  has_many :hubs
  has_many :pages
  has_many :posts
  has_many :blogs
  has_many :notes
  has_many :recipes
  has_many :articles

  # validations
  before_validation :prepare_login, on: :create

  validates :login,    presence: true, uniqueness: true
  validates :email,    presence: true, uniqueness: true
  validates :password, presence: true, on: :create

  class << self
    def root
      @@root ||= User.first
    end

    def create_admin!
      user = new(
        login: :admin,
        email: "admin@site.com",
        password: "qwerty",
        role: Role.with_name(:admin)
      )
      user.save!
      user
    end
  end

  def admin?
    self == User.root
  end

  # TheComments methods
  def comments_admin?
    self == User.root
  end

  def comments_moderator? comment
    admin? || id == comment.holder_id
  end

  def commentable_title
    login
  end

  def commentable_path
    [self.class.to_s.tableize, login].join('/')
  end
  # ~ TheComments methods

  def role_name
    role.try(:name)
  end

  def recalculate_all_attached_files!
    # Recalculate all user counters here
  end

  # Select an available hubs
  # 
  # Admin has: all + for_manage hubs
  #
  # Any User has: hubs defined in his TheRole
  # with section "available_hubs"
  def available_hubs object = nil
    return Hub.none if object.nil?

    ctrl_name = object.ctrl_name
    scope = ctrl_name.blank? ? :all : [:of_, ctrl_name]

    return Hub.send(*scope).for_manage if admin?
    
    section = role.to_hash.try(:[], 'available_hubs')
    return Hub.none if section.blank?

    keys = section.select{|k, v| v == true }.keys
    keys.map!{|item| item.to_slug_param }

    Hub.friendly_where(keys).published_set.send(*scope)
  end

  private

  def prepare_login
    self.login = self.login.to_s.to_slug_param
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_require,  only: [:cabinet]
  before_action :role_required, only: [:cabinet]

  def index
    @users = User.includes(:role).order("role_id ASC").page(params[:page])
  end

  def show
    @user = User.where(login: params[:id]).first
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:login, :email, :password)
    if @user.save
      login(@user.login, @user.open_password, false)
      redirect_to cabinet_url, notice: t('.created')
    else
      render :new
    end
  end

  # secured
  def cabinet; end
end

app/views/open_cook/users/cabinet.html.haml
.users_cabinet
  %h3= t ".cabinet", login: @user.login

  - if current_user.any_role?(posts: :new, pages: :new)
    .fn_block
      %h4= t '.create'

      %ul.marked_list
        - if current_user.has_role?(:posts, :new)
          %li= link_to t('.new_post'), new_post_url

        - if current_user.has_role?(:pages, :new)
          %li= link_to t('.new_page'), new_page_url

  - if current_user.any_role?(posts: :manage, pages: :manage)
    .fn_block
      %h4= t '.pubs_manage'

      %ul.marked_list
        - if current_user.has_role?(:posts, :manage)
          %li= link_to t('.my_posts'), manage_user_posts_url(@user)

        - if current_user.has_role?(:pages, :manage)
          %li= link_to t('.my_pages'), manage_user_pages_url(@user)

  - if current_user.has_role?(:posts, :my)
    .fn_block
      %h4= t '.show'

      %ul.marked_list
        - if current_user.has_role?(:posts, :my)
          %li= link_to t('.my_post_list'),  user_posts_url(@user)

  - if @user.has_role?(:hubs, :manage)
    .fn_block
      %h4= t '.hubs_manage'

      %ul.marked_list
        %li= link_to t('.hubs'), manage_hubs_url

  .fn_block
    %h4= t '.comments'
    
    %ul.marked_list
      %li
        = link_to [:manage, :comments] do
          = t(".incoming_comments") + "(+#{@user.draft_comcoms_count})"

  - if @user.has_role?(:roles, :manage)
    .fn_block
      %h4= t '.users_and_roles'

      %ul.marked_list
        %li= link_to t('.users'), users_url
        %li= link_to t('.roles'), admin_roles_url