config/routes.rb
TheApp::Application.routes.draw do
  root to: 'welcome#index'

  # Legacy Urls
  # /recipes/rc56797---lavandovyy-limonad
  # /recipes/tags/milk
  get "recipes/:id" => "welcome#legacy_post"
  get "recipes/tag/:id", to: redirect { |params, request| URI.encode "#{request.protocol + request.host_with_port}/tag/#{params[:id]}" }

  # Login system
  get    "login"    => "sessions#new",     as: :login
  delete "logout"   => "sessions#destroy", as: :logout
  get    "signup"   => "users#new",        as: :signup
  post   "sessions" => "sessions#create",  as: :sessions

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # Direct routes
  %w{ hubs pages posts }.each do |name|
    resources name, concerns: :sortable_tree
  end

  resources :hubs do
    post :expand_node, on: :collection
    # post :selector,    on: :collection
  end

  # Users
  resources :users, only: [:index, :show, :create] do
    %w{ hubs pages posts }.each do |name|
      resources name, concerns: :sortable_tree
    end
  end

  # tags
  get "tag/:tag" => "posts#tag", as: :tag

  # /users/:user_id/manage/recipes
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage

  # TheStorages
  patch '/image_processor/rotate_left/:id',  as: :rotate_left,  to: 'image_processor#rotate_left'
  patch '/image_processor/rotate_right/:id', as: :rotate_right, to: 'image_processor#rotate_right'
  patch '/image_processor/crop_image',       as: :crop_image,   to: 'image_processor#crop_image'

  get "/:id" => 'hubs#system_section', as: :system_hub

  # Main image
  delete 'delete_main_image/:storage_type/:storage_id'   => "attached_files#delete_main_image",      as: :delete_main_image
  patch  'main_image_to_left/:storage_type/:storage_id'  => "attached_files#main_image_to_left",     as: :main_image_to_left
  patch  'main_image_to_right/:storage_type/:storage_id' => "attached_files#main_image_to_right",    as: :main_image_to_right
  post   'crop_image_for_preview'                        => "attached_files#crop_image_for_preview", as: :crop_image_for_preview
end

app/views/bootstrap3/layouts/widgets/_express_nav.html.haml
- if content_for? :express_nav
  .widget.express_nav
    %h3 Навигация
    .holder
      .wrp= yield :express_nav

app/views/bootstrap3/layouts/widgets/_hubs.html.haml
- unless @sub_hubs.blank?
  .panel.panel-success
    .panel-heading
      %h3 Хабы

    .panel-body
      - @sub_hubs.each do |hub|
        - current = (@hub == hub) ? :current : nil
        = link_to hub_url(hub.slug), class: current do
          %p
            = hub.title
            %b
              (#{hub.pubs_published_count})

app/views/bootstrap3/layouts/widgets/_recent_comments.html.haml
- comments = Comment.with_state(:published).where(commentable_state: :published).limit(5)

- unless comments.blank?
  .widget.recent_comments
    %h3 Новые комментарии
    .holder
      .wrp
        - comments.each do |comment|
          .comment
            %p.title= link_to comment.commentable_title, comment.commentable_url
            %p.content= comment.content
            %p.info
              = comment.title
              от
              = comment.created_at.strftime('%d.%m.%Y')
      .comments.hidden
        %p= link_to "Все комментарии", comments_path
            

app/views/bootstrap3/layouts/widgets/_tag_search.html.haml
- tags = Post.tag_counts

- unless tags.blank?
  .widget._right.tag_search
    %h3 Поиск тэгов
    .holder
      .wrp
        = text_field_tag :tag_word, '', placeholder: "Что ищем?"
        .basic
          - _tags = tags.sample(10)
          - tag_cloud(_tags, %w(mini small normal big)) do |tag, css_class|
            %p
              = link_to tag_path(tag.name), class: css_class do
                = tag.name + " (#{tag.count})"
        .collection.hidden
          - tag_cloud(tags, %w(mini small normal big)) do |tag, css_class|
            %p{ data: { tag: tag.name, count: tag.count } }
              = link_to tag_path(tag.name), class: css_class do
                = tag.name + " (#{tag.count})"
        .result.hidden

app/views/bootstrap3/layouts/widgets/_tags.html.haml
- tags = tags_str.split ','

- unless tags.blank?
  .panel.panel-success
    .panel-heading
      %h3 Тэги

    .panel-body
      - tags.each do |tag|
        %p= link_to tag, tag_url(tag)